### ISSUE TITLE
Function Extract not working

### ISSUE THREAD

**Issue by EoD** [LucHermitte/vim-refactor#1]
I have the following code:
```c++
  1 #include <stdio>
  2 
  3 int main() {
  4     
  5     int a;
  6     int b;
  7     
  8     std::cout << a << b;
  9 }
 ```
I entered visual mode and marked line 5, 6 and 7. Then I pressed ``<c-x>f`` and entered a new Name. This causes the following error:
```
Name for the function to extract: test3 lines yanked
Error detected while processing function lh#refactor#extract_function[18]..<SNR>117_SearchParameters[134]..lh#refactor#
gui_em#open:
line    8:
E117: Unknown function: MuTemplate
Press ENTER or type command to continue
```

I installed your plugin via vundle, by adding the following lines to my ``.vimrc``:
```
 " C++ refactoring
 Bundle 'LucHermitte/lh-vim-lib'
 Bundle 'LucHermitte/lh-tags'
 Bundle 'LucHermitte/lh-dev'
 Bundle 'LucHermitte/lh-brackets'
 Bundle 'LucHermitte/vim-refactor'
```

**Comment by LucHermitte** [comment]
This function is installed in my mu-template plugin.
It seems I forgot to document the dependency on mu-template the day I've patched the extract function refactoring.

So I'll have to document the requirement and fix the dependency files for VAM and vim-flavour.
And you'll need to install mu-template as well. Sorry.

**Comment by TamaMcGlinn** [comment]
Is this still an issue? The readme still doesn't say to install mu-template, but I got a different error when I tried the same as OP, as `<SNR>394_Callstack` is not defined:

![Screenshot from 2021-08-03 10-28-57](https://user-images.githubusercontent.com/5008897/127983881-15e925cb-594f-4379-b9f0-488b7a58deb5.png)

**Comment by LucHermitte** [comment]
@TamaMcGlinn oddly enough I've missed this missing function in lh-tags. It should be fixed now. I've also documented the missing optional dependency to mu-template. VimFlavor and VAM addon-info.json files were already correct.

Dont hesitate to open new issues if you encounter other errors. However please note this _function extraction_ feature is highly experimental and in imprecise as it relies on ctags to find local variables, parameters and so on.
